#!/usr/bin/env python3
"""临时脚本：构造 rl-at-1t-scale 翻译块并批量翻译（原文全保留）。"""
import json, sys, os
sys.path.insert(0, r"C:/Users/twfehh7/AppData/Local/hermes/skills/content-creation/wechat-article-sop/scripts")
from llm_utils import translate_batch

# 从 full_text.txt 重构原文块（页面提取的文本段落）
txt = open(r"D:/06_Hermes/articles/rl-at-1t-scale/full_text.txt", encoding="utf-8").read()
lines = [l.rstrip() for l in txt.split("\n")]

# 手动按 DOM 结构构造内容块（依据 page.html 的 parse 结果）
# token 顺序: [6]intro1, [7]img(hero-fig01), [8]intro2, [9]glm-cmd引, [10]code, 
#   [11]h2 agentic, [12]p, [13]img(async-fig02), [14]p, [15]img(weight-fig03), [16]p, [17]p,
#   [18]h2 inference, [19]p, [20]h3 fp8, [21]p, [22]h3 wideep, [23]p, [24]p, [25]img(wideep-fig04)
#   [26]h3 pd, [27]p,[28]p,[29]p, [30]img(pd-fig05)
#   [31]h3 kv, [32]p,[33]p,[34]p, [35]h3 routing,[36]p,[37]p,[38]p,[39]p, [40]img(routing-fig06),[41]p
#   [42]h3 router-replay,[43]p, [44]img(r3-fig07), [45]p,[46]p,[47]p
#   [48]h2 training,[49]p, [50]h3 parallelism,[51]p,[52]p,[53]p, [54]img(fsdp-fig08)
#   [55]p,[56]p,[57]p, [58]img(ep-fig09), [59]p,[60]p,[61]p,[62]p,[63]p,[64]p, [65]img(cp-fig10)
#   [66]h3 glm5-dsa,[67]p, [68]h3 fp8-train,[69]p, [70]img(fp8-fig11)
#   [71]h2 future,[72]p, [73]h2 hiring,[74]p,[75]p,[76]p,[77]p
#
# 为译准确，正文段落直接用 full_text.txt 分段拿完整文本（第 8~130 行之间）
# 这里直接手工列出待翻译 text 块（id -> 完整原文）

blocks = [
 {"id":1,"type":"text","content":"RL at 1T Scale: prime-rl Performance Deep Dive"},
 {"id":2,"type":"text","content":"Today we are releasing prime-rl version 0.6.0. This version enables us (and you) to train models of trillion-parameter scale on heavy agentic workloads at the highest efficiency. We have been relentlessly optimizing our RL infrastructure to maximize performance on large MoE models, reducing the cost, time and suffering required to post-train OSS models on agentic workflows. We are able to train GLM-5 on SWE tasks at up to 131k sequence length, with sub-5-minute step times and a batch size of 256 rollouts, on only 28 H200 nodes."},
 {"id":3,"type":"text","content":"In this blog we will cover all the optimizations that lead to these results, from low-precision inference and training to prefill and decode disaggregated inference deployment. We will take zai-org/GLM-5.1 as our model example, but our optimizations translate to any large mixture-of-experts model, such as moonshotai/Kimi-K2.7-Code, nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16, etc."},
 {"id":4,"type":"text","content":"GLM-5.1 training can be run with a single command on a Slurm cluster using prime-rl:"},
 {"id":6,"type":"text","content":"Agentic RL from first principles"},
 {"id":7,"type":"text","content":"prime-rl has been built from the ground up to allow for efficient agentic post-training, embracing asynchronous RL. Agentic tasks often have long-tail outliers; these rollouts can take up to a few hours, especially long-horizon coding tasks. Delaying the policy update until these rollouts finish would under-utilize GPUs and hurt performance. Asynchronous RL solves this by allowing the inference policy to be updated as soon as the optimizer step is finished on the trainer deployment. In asynchronous RL the trainer and inference are disaggregated and can be optimized independently."},
 {"id":8,"type":"text","content":"There is an inherent synchronization point between trainer and inference \u2014 the policy update. The rollout policy is updated with new weights after each optimizer step. In prime-rl we update the weights as soon as the new set is available. To not slow down inference, the active prefix cache is not reset for already dispatched rollouts \u2014 these rollouts will be comprised of tokens generated by various policies, with the KV cache also being produced by multiple versions. However, new rollouts, even when they share a prefix with older ones, re-populate their own KV cache; we use a KV-cache salt to force this. Finally, requests are dropped if they were generated by too old a policy; you control this with the max_off_policy_steps value."},
 {"id":9,"type":"text","content":"These interactions create an interesting problem from the systems optimization perspective: how to optimize 2 systems \u2014 trainer and inference \u2014 while keeping them compatible."},
 {"id":10,"type":"text","content":"In the following sections, we will dissect both of these systems and what optimizations we've done."},
 {"id":11,"type":"text","content":"Inference"},
 {"id":12,"type":"text","content":"Inference is the critical part of the RL training lifecycle. That's where the model interacts with its environment, producing rollouts that are evaluated and assigned a reward. Some of these features already exist in inference frameworks; for others we work closely with frameworks like vLLM and Dynamo, with one goal: to give the community the highest-performance inference with validated, easy-to-use recipes."},
 {"id":13,"type":"text","content":"FP8 Inference"},
 {"id":14,"type":"text","content":"Inference throughput is usually the bottleneck of your RL system. Inference throughput heavily benefits from lower precision on both prefill and decode deployments. We heavily utilize FP8 inference, together with optimized kernels from DeepEP and DeepGEMM to achieve lower latency and higher throughput."},
 {"id":15,"type":"text","content":"Wide Expert Parallelism"},
 {"id":16,"type":"text","content":"In other articles about inference performance, you might have noticed a lot of focus on minimizing latency, to achieve the highest interactivity for the users. This is not the case with RL \u2014 our primary focus is maximizing throughput, while keeping latency somewhat bounded (more on that later)."},
 {"id":17,"type":"text","content":"One of the best configurations to achieve this is Wide EP \u2014 large-scale expert parallelism, often spanning \u226532 GPUs. To maximize throughput, we combine this strategy with a large data-parallel rank \u2014 for example 32 \u2014 creating a large group of GPUs, each holding separate experts, each serving as a separate endpoint. Synchronization happens per-layer, in dispatch and combine operations respectively."},
 {"id":18,"type":"text","content":"Prefill and Decode Disaggregation"},
 {"id":19,"type":"text","content":"Prefill throughput is a big bottleneck of agentic rollouts \u2014 some combinations of model\u2194env pairs produce as much as a 4:1 prefill:decode token ratio. Having the same inference workers serve both prefill and decode requests would increase E2E latency, significantly reducing the benefits of PipelineRL."},
 {"id":20,"type":"text","content":"As mentioned before, the priority for RL is maximizing inference throughput, not minimizing latency. However, if latency grows large due to inference batches getting dominated by prefill requests, \"grouping\" of finished inference rollouts can be observed, leading to low overlap of trainer and inference steps."},
 {"id":21,"type":"text","content":"With prime-rl you can seamlessly use P/D disaggregation. When prefill and decode workers are separated, long prefill requests (lengthy tool outputs, etc.) do not throttle the decode workers, letting them progress with predictable latency. This completes model turns faster, tool-calls then reach sandbox execution faster, and the cycle repeats, sometimes across 100s of turns."},
 {"id":22,"type":"text","content":"KV cache management"},
 {"id":23,"type":"text","content":"Maximizing throughput requires high concurrency. That in turn requires a lot of KV cache space. If there is not enough space, KV cache thrashing and a low prefix-cache hit rate can occur, lowering the throughput. prime-rl stays on top of the newest features in inference frameworks, supporting them E2E \u2014 one of these cases is KV cache offloading."},
 {"id":24,"type":"text","content":"We support tiered KV cache offloading to both CPU and disk using both native vLLM offloading and Mooncake. With more KV cache space, we can increase concurrency, amortizing more of the trainer costs."},
 {"id":25,"type":"text","content":"There are 2 main differences between each of these approaches:\nvLLM native offloading \u2014 a simple approach, creates a single CPU/disk pool per worker (DP rank); only this worker can in turn load from this cache.\nMooncake Store instead works as a centralized store, that pools RAM/disk from all the clients (nodes) into 1 large pool, that can then be reached from any inference worker from any node \u2014 this provides a significant advantage, especially when using more sophisticated routing strategies."},
 {"id":26,"type":"text","content":"Request Routing"},
 {"id":27,"type":"text","content":"To tie everything together, inference requests need to be routed efficiently to allow for efficient prefix reuse, load-aware routing, etc."},
 {"id":28,"type":"text","content":"The default routing option in prime-rl is our fork of vllm-router, a minimal, lightweight solution that delivers strong performance with minimal configuration overhead. Depending on your requirements, you can choose your own routing strategies optimized for load balancing, KV cache reuse, or other objectives."},
 {"id":29,"type":"text","content":"We also support the NVIDIA Dynamo router as a drop-in alternative. This allows us to develop and deploy more sophisticated routing strategies for larger-scale runs. These strategies combine different factors, such as KV cache reuse, queue depth, KV cache utilization or current load, based on the live metrics from the inference workers, to compute a score given to each worker. Workers then get selected based on a policy and their scores."},
 {"id":30,"type":"text","content":"Combined with Mooncake Store, which serves as a centralized KV cache offloading layer, this enables prefix cache hits across replicas while distributing the load fairly and reacting to live inference metrics."},
 {"id":31,"type":"text","content":"We are also actively collaborating with the vLLM and Dynamo teams on continuously improving the routing solutions, bringing more performance to inference."},
 {"id":32,"type":"text","content":"Router replay"},
 {"id":33,"type":"text","content":"Trainer\u2194inference mismatch silently kills your RL training. To fight this, you can use router replay \u2014 R3 in prime-rl. This works by capturing the routing decisions made during inference and then replaying them directly on the trainer. This effectively reduces KL mismatch between trainer and inference by an order of magnitude, resulting in more stable training."},
 {"id":34,"type":"text","content":"This doesn't come for free \u2014 at large-scale deployments, routed-experts data can reach up to tens of Gbps, creating a large strain on the processing. This caused us a lot of headache, but now prime-rl can serve thousands of concurrent agentic rollouts while processing this data."},
 {"id":35,"type":"text","content":"Routed experts are a large payload of shape [num_layers, top_k, seq_len] which can quickly grow to hundreds of GB, which in turn causes large load on the Python processing \u2014 even seemingly simple operations, such as converting responses into Python dictionaries, can cause significant event-loop lag and CPU bottlenecks. To eliminate this overhead, prime-rl treats routed experts as an opaque payload where the only processing is handled by heavily optimized PyTorch operations, reducing the CPU strain."},
 {"id":36,"type":"text","content":"Router Replay is fully compatible with other inference optimizations, including P/D disaggregation, allowing you to deploy production-ready stacks with ease."},
 {"id":37,"type":"text","content":"Training"},
 {"id":38,"type":"text","content":"Our trainer is based on torchtitan \u2014 a high-performance PyTorch-native large-scale training code-base. We've adapted a lot of our trainer code from torchtitan, spanning features like FSDP, EP and various other abstractions, while adding our own touches and improvements."},
 {"id":39,"type":"text","content":"Parallelism"},
 {"id":40,"type":"text","content":"prime-rl mostly relies on 3-D parallelism, to be exact: FSDP, CP and EP. Each of these has its own use-cases, benefits and drawbacks. To get a large-scale run going smoothly, you need to use a combination of them in varying degrees. For our GLM-5 case study, we employ all 3."},
 {"id":41,"type":"text","content":"Let's do a short refresher on all of them."},
 {"id":42,"type":"text","content":"FSDP. Fully Sharded Data Parallel is our baseline distribution strategy. Parameters, gradients, and optimizer states are sharded across the data-parallel ranks and gathered on demand during the forward and backward pass. For a model with 1T+ parameters, this is required to amortize the memory footprint of the full optimizer state or parameters. We utilize fully_shard (FSDP2) from PyTorch as our FSDP implementation; this allows easy composition with other strategies, as discussed further."},
 {"id":43,"type":"text","content":"Expert Parallelism (EP). Even after FSDP, large model layers are still way too large to effectively fit into single-GPU HBM after an FSDP all-gather. With 78 layers, 800B params and master weights in float32, an all-gather of a single layer requires roughly (800B \u00d7 4) / 78 \u2248 40GB buffer. With FSDP overlap of 1 layer, this would require ~80GB of memory just for active layer weights."},
 {"id":44,"type":"text","content":"That's where EP comes in: instead of all-gathering the full layer, we set a separate inner EP degree, for example EP=8, across which experts won't be gathered. Instead, tokens will be dispatched and combined using all2all primitives. With experts being the major contributor to the layer memory footprint, this significantly reduces active memory."},
 {"id":45,"type":"text","content":"In prime-rl we allow 2 separate EP configurations \u2014 torch-native all2all and DeepEP. From our observations, torch-native provides slightly better throughput on a single-node EP span (i.e. EP=8), but drops significantly when EP spans across nodes. This is where using DeepEP becomes faster by a large margin."},
 {"id":46,"type":"text","content":"Context Parallelism (CP). At 131k+ sequence length, intermediate activations \u2014 not parameters \u2014 become the dominant memory cost. Context parallelism shards the sequence dimension across ranks to reduce the per-GPU activation."},
 {"id":47,"type":"text","content":"In prime-rl we support context parallelism for all of our custom models. We support 2 main ways to use context parallelism:\nRing Attention \u2014 The batch is sequence-sharded throughout the whole model forward. When core attention is reached, each rank holds its shard of Q, K and V, while also processing K and V from other ranks in a ring-like pattern.\nUlysses \u2014 As in ring attention, data is sequence-length sharded through the whole model forward. When attention is reached, all2all operations flip the layout from sequence-sharded to head-sharded and attention is then computed across the head dimension. Once attention computation completes, the layout is again swapped back with another all2all. This works nicely with most of the non-standard attentions (linear attention, Mamba, etc.) and is our default."},
 {"id":48,"type":"text","content":"However, there are some exceptions to this \u2014 one of them being DSA as used in GLM-5."},
 {"id":49,"type":"text","content":"For models with attentions that can't be parallelized with both Ulysses and Ring Attention, we write custom context-parallel implementations, GLM-5 being one of them."},
 {"id":50,"type":"text","content":"Our context parallelism implementation keeps the sequences sharded and computes projections. After this, K and V are gathered \u2014 this is cheap as they are projected into a latent space \u2014 to allow the indexer to see the full sequence. The indexer computes sparse indices for the global sequence and core attention is computed on these indices. As DSA has fixed top_k, the cost of this is also fixed (except for the memory cost of KV, which is negligible as discussed before)."},
 {"id":51,"type":"text","content":"This scheme allows for only a single all-gather collective per attention layer, keeping the costs at a minimum."},
 {"id":52,"type":"text","content":"GLM-5 DSA"},
 {"id":53,"type":"text","content":"To compute DSA efficiently, we use custom kernels, heavily based on the reference implementations and adapted to our needs, providing both fast forward and backward."},
 {"id":54,"type":"text","content":"FP8 training"},
 {"id":55,"type":"text","content":"As noted earlier, trainer\u2194inference mismatch can hurt your training. To fight this, we use DeepGEMM kernels to perform block-scaled FP8, as proposed by DeepSeek V3. This, contrary to popular belief, doesn't really increase the throughput, due to quantization overhead (except for specific configurations); however, it heavily decreases KL mismatch between trainer and inference, as both now use the same precision, and even the same kernels in some cases. This in turn leads to more stable training."},
 {"id":56,"type":"text","content":"Future work"},
 {"id":57,"type":"text","content":"We continue exploring other ways to improve the performance of our RL engine, actively collaborating with other frameworks \u2014 notably vLLM, Dynamo and llm-d to speed up the inference side, or PyTorch for a blazingly fast trainer \u2014 exploring techniques such as speculative decoding, NVFP4 training and inference, or infrastructure improvements like fault tolerance, elastic scaling, and sub-1-second trainer\u2194inference weight transfer of huge models."},
 {"id":58,"type":"text","content":"We're hiring!"},
 {"id":59,"type":"text","content":"Large-scale agentic RL is, in our opinion, one of the most exciting systems challenges in AI today. Building an efficient RL stack requires optimizing a wide range of components, both individually and as a cohesive system: training, inference, request routing, weight broadcasting, in-flight weight updates, environments, code execution sandboxes, and much more."},
 {"id":60,"type":"text","content":"At scale, every source of overhead matters. Success comes from understanding how these systems interact, identifying bottlenecks, and relentlessly pushing efficiency across the entire stack."},
 {"id":61,"type":"text","content":"If this sounds interesting to you, and you'd like your day-to-day work to involve building and optimizing these systems at massive scale, experimenting with new distributed training and inference techniques, and squeezing every last bit of performance out of thousands of GPUs, we'd love to hear from you."},
]

# 翻译（code 块不翻译）
json.dump(blocks, open(r"D:/06_Hermes/articles/rl-at-1t-scale/_extract_blocks.json","w",encoding="utf-8"), ensure_ascii=False, indent=2)

to_translate = [b for b in blocks if b["type"]=="text"]
done = {}
if os.path.exists(r"D:/06_Hermes/articles/rl-at-1t-scale/_translations.json"):
    done = json.load(open(r"D:/06_Hermes/articles/rl-at-1t-scale/_translations.json",encoding="utf-8"))
todo = [b for b in to_translate if str(b["id"]) not in done]
print(f"待翻译 {len(todo)}/{len(to_translate)} 块", flush=True)
CHUNK=30
for c in range(0, len(todo), CHUNK):
    chunk=todo[c:c+CHUNK]
    print(f"翻译 chunk {c//CHUNK+1} ({len(chunk)}块)", flush=True)
    try:
        tr = translate_batch(chunk, batch_size=8)
        for t in tr: done[str(t["id"])]=t["content"]
    except Exception as e:
        print(f"chunk失败 {e}，逐段回退", flush=True)
        from llm_utils import translate
        for b in chunk:
            try: done[str(b["id"])]=translate(b["content"], stream=False)
            except Exception as e2: done[str(b["id"])]=b["content"]; print(f"  {b['id']}失败{e2}",flush=True)
    json.dump(done, open(r"D:/06_Hermes/articles/rl-at-1t-scale/_translations.json","w",encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"  检查点 {len(done)}/{len(to_translate)}", flush=True)
print("翻译完成", flush=True)
