import re, io
t = io.open('D:/06_Hermes/articles/cuda-rust-two-tracks/article.html', encoding='utf-8').read()
print('pre:', t.count('<pre'))
srcs = re.findall(r'<img[^>]+src="([^"]+)"', t)
print('img:', len(srcs), srcs)
print('h2:', t.count('<h2'), 'h3:', t.count('<h3'))
print('strong:', t.count('<strong'))
print('figcaption:', t.count('<figcaption'))
print('dash:', len(re.findall(r'——|—', t)))
print('portal idx:', t.find('portal-title'), 'jieyu idx:', t.find('background:#f5f0eb'), 'ref idx:', t.find('参考：'))
print('a tags:', len(re.findall(r'<a ', t)))
print('span7px:', t.count('font-size:7px'))
print('inline code:', t.count('background:#f3f4f5'))
print('quote card:', t.count('background:#f5f8fb'))
print('body img refs fig:', re.findall(r'src="(fig\d+\.png)"', t))
